import manifest from "../../public/skill/manifest.json";
import { SITE_URL } from "@/config/brand.generated";

/**
 * AGENT SKILLS — the website's one reader of the consumer skills' manifest.
 *
 * public/skill/manifest.json is GENERATED by scripts/generate-agent-skill.mjs
 * (which skills exist, a one-line summary of each, and the files each one
 * holds) and is the same file `npx <pkg> init` fetches to decide what to
 * install. Every surface that names a skill or one of its files (the
 * get-started page's curl snippet, llms.txt, the MCP setup text) builds it
 * from here, so a new skill or file reaches all of them with no second
 * edit. scripts/validate-agent-skill.mjs fails the build on a surface that
 * spells a skill path by hand instead.
 */
export interface AgentSkill {
  /** The folder name, under /skill/ on the site and .claude/skills/ in a project. */
  name: string;
  /** What the skill is for, as one fragment ending in a full stop. */
  summary: string;
  /** The skill's files, relative to its folder. */
  files: readonly string[];
}

/** Every published consumer skill, in install order. */
export const AGENT_SKILLS: readonly AgentSkill[] = manifest.skills;

/** The official consumer-skill count. */
export const AGENT_SKILL_COUNT: number = AGENT_SKILLS.length;

/** Where the manifest itself is served. */
export const AGENT_SKILL_MANIFEST_URL = `${SITE_URL}/skill/manifest.json`;

/** The served URL of one file of one skill. */
export function skillFileUrl(skill: AgentSkill, file: string): string {
  return `${SITE_URL}/skill/${skill.name}/${file}`;
}

/** The by-hand install: one curl per file, into the folder the init bin uses. */
export function skillCurlSnippet(): string {
  return AGENT_SKILLS.flatMap((skill) =>
    skill.files.map(
      (file) =>
        `curl --create-dirs -o .claude/skills/${skill.name}/${file} ${skillFileUrl(skill, file)}`
    )
  ).join("\n");
}
