/**
 * GENERATED FILE — do not edit.
 * Built from src/components/registry.json by scripts/generate-library-barrel.mjs
 * (validate-registry chain). recharts-backed modules live in charts.ts, not here — recharts is an optional peer.
 */
export * from './components/Accordion/Accordion';
export * from './components/AgentPlan/AgentPlan';
export * from './components/AgentStatus/AgentStatus';
export * from './components/AgentStatus/AgentStatusPatterns';
export * from './components/AiButton/AiButton';
export * from './components/Alert/Alert';
export * from './components/AlertDialog/AlertDialog';
export * from './components/AnchorNav/AnchorNav';
export * from './components/AnimatedNumber/AnimatedNumber';
export * from './components/AppLayout/AppLayout';
export * from './components/AppSidebar/AppSidebar';
export * from './components/Avatar/Avatar';
export * from './components/AvatarGroup/AvatarGroup';
export * from './components/Badge/Badge';
export * from './components/Banner/Banner';
export * from './components/Breadcrumb/Breadcrumb';
export * from './components/Button/Button';
export * from './components/ButtonGroup/ButtonGroup';
export * from './components/Card/Card';
export * from './components/CardStack/CardStack';
export * from './components/Carousel/Carousel';
export * from './components/ChatHeader/ChatHeader';
export * from './components/ChatMarker/ChatMarker';
export * from './components/ChatMessage/ChatMessage';
export * from './components/ChatThread/ChatThread';
export * from './components/Checkbox/Checkbox';
export * from './components/Chip/Chip';
export * from './components/CircularButton/CircularButton';
export * from './components/CodeBlock/CodeBlock';
export * from './components/CodeDiff/CodeDiff';
export * from './components/ColorPicker/ColorPicker';
export * from './components/Combobox/Combobox';
export * from './components/CommandPalette/CommandPalette';
export * from './components/Composer/Composer';
export * from './components/ContactCard/ContactCard';
export * from './components/ContextMenu/ContextMenu';
export * from './components/ContributionGraph/ContributionGraph';
export * from './components/DataTable/DataTable';
export * from './components/DateInput/DateInput';
export * from './components/DatePicker/DatePicker';
export * from './components/Dialog/Dialog';
export * from './components/Divider/Divider';
export * from './components/DocumentChip/DocumentChip';
export * from './components/Drawer/Drawer';
export * from './components/Dropdown/Dropdown';
export * from './components/DropdownMenu/DropdownMenu';
export * from './components/EmptyState/EmptyState';
export * from './components/EntityCard/EntityCard';
export * from './components/EventCalendar/EventCalendar';
export * from './components/Field/Field';
export * from './components/Field/FieldContext';
export * from './components/Figure/Figure';
export * from './components/FileInput/FileInput';
export * from './components/FilterBar/FilterBar';
export * from './components/GanttChart/GanttChart';
export * from './components/Gauge/Gauge';
export * from './components/Globe/Globe';
export * from './components/HoverCard/HoverCard';
export * from './components/ImageCompare/ImageCompare';
export * from './components/Input/Input';
export * from './components/Instructions/Instructions';
export * from './components/InterruptCard/InterruptCard';
export * from './components/Kbd/Kbd';
export * from './components/LegendTile/LegendTile';
export * from './components/Lightbox/Lightbox';
export * from './components/LinkList/LinkList';
export * from './components/MapCallout/MapCallout';
export * from './components/MapLegend/MapLegend';
export * from './components/MessageActions/MessageActions';
export * from './components/MessageCard/MessageCard';
export * from './components/Meter/Meter';
export * from './components/ModelPicker/ModelPicker';
export * from './components/Nav/Nav';
export * from './components/NavList/NavList';
export * from './components/NotificationCenter/NotificationCenter';
export * from './components/NumberInput/NumberInput';
export * from './components/Pagination/Pagination';
export * from './components/Panel/Panel';
export * from './components/PinInput/PinInput';
export * from './components/Popover/Popover';
export * from './components/ProgressBar/ProgressBar';
export * from './components/PromptSuggestions/PromptSuggestions';
export * from './components/Prose/Prose';
export * from './components/Quote/Quote';
export * from './components/RadioButton/RadioButton';
export * from './components/Rating/Rating';
export * from './components/Reasoning/Reasoning';
export * from './components/RichDropdown/RichDropdown';
export * from './components/SectionTitle/SectionTitle';
export * from './components/SegmentedControl/SegmentedControl';
export * from './components/SelectionCard/SelectionCard';
export * from './components/ShaderField/ShaderField';
export * from './components/Skeleton/Skeleton';
export * from './components/Slider/Slider';
export * from './components/SourceChip/SourceChip';
export * from './components/SourceTrail/SourceTrail';
export * from './components/Sparkline/Sparkline';
export * from './components/Spinner/Spinner';
export * from './components/SplitButton/SplitButton';
export * from './components/SplitPane/SplitPane';
export * from './components/Stat/Stat';
export * from './components/StatusDot/StatusDot';
export * from './components/Stepper/Stepper';
export * from './components/StreamingText/StreamingText';
export * from './components/Swatch/Swatch';
export * from './components/Table/Table';
export * from './components/Tabs/Tabs';
export * from './components/TagInput/TagInput';
export * from './components/Textarea/Textarea';
export * from './components/ThreadPanel/ThreadPanel';
export * from './components/ThreadTabs/ThreadTabs';
export * from './components/Timeline/Timeline';
export * from './components/TimePicker/TimePicker';
export * from './components/Toast/Toast';
export * from './components/ToggleGroup/ToggleGroup';
export * from './components/ToggleSwitch/ToggleSwitch';
export * from './components/Toolbar/Toolbar';
export * from './components/ToolCall/ToolCall';
export * from './components/Tooltip/Tooltip';
export * from './components/TreeView/TreeView';
export * from './components/UsageCard/UsageCard';
export * from './components/Waveform/Waveform';
export * from './components/WorldMap/WorldMap';

export {
  componentRegistry,
  componentMetadata,
  componentCategories,
  componentCategoryMetadata,
  COMPONENT_COUNT,
} from './components/registry';
export type { ComponentMeta, ComponentCategoryMeta } from './components/registry';
export { tokenRegistry, TOKEN_COUNT, TOKEN_COUNTS } from './tokens/registry';
